# Generated by Django 3.2 on 2021-09-03 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzeria_name', models.CharField(max_length=32)),
                ('city', models.CharField(blank=True, max_length=16)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')])),
                ('description', models.TextField(blank=True)),
                ('logo_image', models.ImageField(blank=True, default='pizzeriaImages/default.png', upload_to='pizzeriaImages')),
                ('email', models.EmailField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
