# Generated by Django 3.2 on 2021-09-07 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_store', '0002_alter_pizzeria_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pizzeriaImages/default.png', upload_to='photos')),
                ('image_title', models.CharField(blank=True, max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pizzeria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pizza_store.pizzeria')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
