name: Pylint

on:
  # Trigger workflow on pull request, but only for PRs
  # merging into master and develop branches
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
         pylint pakx_video
